{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import dash\n",
    "from dash.dependencies import Input, Output\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\dash.py\", line 1093, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\_validate.py\", line 339, in validate_layout\n",
      "    \"\"\"\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called.\n",
      "Make sure to set the `layout` attribute of your application\n",
      "before running the server.\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\dash.py\", line 1093, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\_validate.py\", line 339, in validate_layout\n",
      "    \"\"\"\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called.\n",
      "Make sure to set the `layout` attribute of your application\n",
      "before running the server.\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\dash.py\", line 1093, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\_validate.py\", line 339, in validate_layout\n",
      "    \"\"\"\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called.\n",
      "Make sure to set the `layout` attribute of your application\n",
      "before running the server.\n",
      "Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\dash.py\", line 1093, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\_validate.py\", line 339, in validate_layout\n",
      "    \"\"\"\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called.\n",
      "Make sure to set the `layout` attribute of your application\n",
      "before running the server.\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\dash.py\", line 1093, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\_validate.py\", line 339, in validate_layout\n",
      "    \"\"\"\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called.\n",
      "Make sure to set the `layout` attribute of your application\n",
      "before running the server.\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\dash.py\", line 1093, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\_validate.py\", line 339, in validate_layout\n",
      "    \"\"\"\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called.\n",
      "Make sure to set the `layout` attribute of your application\n",
      "before running the server.\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\dash.py\", line 1093, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\_validate.py\", line 339, in validate_layout\n",
      "    \"\"\"\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called.\n",
      "Make sure to set the `layout` attribute of your application\n",
      "before running the server.\n",
      "Exception on /favicon.ico [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1945, in full_dispatch_request\n",
      "    self.try_trigger_before_first_request_functions()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\flask\\app.py\", line 1993, in try_trigger_before_first_request_functions\n",
      "    func()\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\dash.py\", line 1093, in _setup_server\n",
      "    _validate.validate_layout(self.layout, self._layout_value())\n",
      "  File \"C:\\Users\\madit\\.conda\\envs\\PythonGPU\\lib\\site-packages\\dash\\_validate.py\", line 339, in validate_layout\n",
      "    \"\"\"\n",
      "dash.exceptions.NoLayoutException: The layout was `None` at the time that `run_server` was called.\n",
      "Make sure to set the `layout` attribute of your application\n",
      "before running the server.\n"
     ]
    }
   ],
   "source": [
    "app = dash.Dash(__name__)\n",
    "server = app.server\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (<ipython-input-6-b98dd47463f7>, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  File \u001b[1;32m\"<ipython-input-6-b98dd47463f7>\"\u001b[1;36m, line \u001b[1;32m1\u001b[0m\n\u001b[1;33m    print(%tb)\u001b[0m\n\u001b[1;37m          ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "global product_df\n",
    "product_df = dbm.read()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
